export const demoProducts = [
  {
    id: 101,
    name: "AirPods Max - Sky Blue",
    description: "The ultimate over-ear personal listening experience, available in five fresh colors. High-fidelity audio and industry-leading Active Noise Cancellation.",
    price: "49,900",
    category: "Audio",
    image: "/products/airpods-max.png",
    featured: true,
    variants: [
      { size: "OS", color: "Sky Blue", stock: 10 },
      { size: "OS", color: "Space Gray", stock: 15 },
    ],
  },
  {
    id: 102,
    name: "Apple Watch Series 10",
    description: "Designed for your daily flow. Thinner, brighter, and faster than ever. The most advanced health and fitness tracker on your wrist.",
    price: "44,900",
    category: "Wearables",
    image: "/products/apple-watch.png",
    featured: true,
    variants: [
      { size: "41mm", color: "Midnight", stock: 20 },
      { size: "45mm", color: "Starlight", stock: 25 },
    ],
  },
  {
    id: 103,
    name: "Vision Pro Premium",
    description: "Experience every feel of real music and spatial computing. The most advanced wearable technology that blends digital content with your physical space.",
    price: "3,49,900",
    category: "Wearables",
    image: "/products/vision-pro.png",
    featured: true,
    variants: [
      { size: "OS", color: "Silver", stock: 5 },
    ],
  },
  {
    id: 104,
    name: "HomePod Mini",
    description: "The total home hub. Room-filling sound with Siri intelligence. A powerful smart speaker that sounds amazing and fits everywhere.",
    price: "9,900",
    category: "Audio",
    image: "/products/homepod-mini.png",
    featured: false,
    variants: [
      { size: "Standard", color: "White", stock: 30 },
      { size: "Standard", color: "Midnight", stock: 25 },
    ],
  },
  {
    id: 105,
    name: "Apple TV 4K",
    description: "The best of TV meets your favorite Apple devices and services. Cinematic 4K Dolby Vision and HDR10+ for the ultimate movie night.",
    price: "14,900",
    category: "TV & Video",
    image: "/products/apple-tv.png",
    featured: false,
    variants: [
      { size: "64GB", color: "Black", stock: 15 },
      { size: "128GB", color: "Black", stock: 10 },
    ],
  },
  {
    id: 106,
    name: "Studio Display",
    description: "A big, beautiful window into new worlds. 27-inch 5K Retina display with a 12MP Ultra Wide camera and six-speaker sound system.",
    price: "1,59,900",
    category: "Accessories",
    image: "/products/studio-display.png",
    featured: true,
    variants: [
      { size: "Standard Glass", color: "Silver", stock: 8 },
    ],
  },
  {
    id: 107,
    name: "MagSafe Battery Pack",
    description: "Snap on. Charge up. Portable power that attaches magnetically to your iPhone for seamless on-the-go charging.",
    price: "9,900",
    category: "Accessories",
    image: "/products/magsafe-battery.png",
    featured: false,
    variants: [
      { size: "OS", color: "White", stock: 50 },
    ],
  },
  {
    id: 108,
    name: "AirPods Pro 2",
    description: "Magic, remastered. Industry-leading Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio.",
    price: "24,900",
    category: "Audio",
    image: "/products/airpods-pro.png",
    featured: true,
    variants: [
      { size: "OS", color: "White", stock: 40 },
    ],
  },
];
